[package]
name = "ecsv"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
strum = { version = "0.26.1", features = ["derive"] }
thiserror = "1.0.57"
